name: Run Newman Tests

on:
  push:
    branches:
      - main  # Chạy khi có commit lên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run booking.postmsn_collection.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.xml
